repos:
  - repo: https://github.com/prettier/prettier
    rev: v3.3.2
    hooks:
      - id: prettier
        files: \.(js|ts|css|html|md|json|yaml|yml)$
        options: --write
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--fix]
        files: \.(py)$
      - id: ruff-format
        files: \.(py)$
