#!/usr/bin/env bash
# Sims 2 bundle builder — no toolchain required, just cat + node (node is only
# used to turn the CSS into a safely-escaped JS string). Edit the files under
# src/ and rerun `./build.sh` to regenerate the served bundle at
# custom_components/sims2ha/frontend/sims2-bundle.js (the path the integration
# serves to browsers).
#
# Vendored dependency: src/vendor/auto-entities.js (MIT, (c) Thomas Lovén,
# https://github.com/thomasloven/lovelace-auto-entities) is bundled in so users
# do NOT need a separate HACS install for the auto-populating dashboards.
set -euo pipefail
cd "$(dirname "$0")"

mkdir -p custom_components/sims2ha/frontend

node -e '
const fs = require("fs");
const read = (p) => fs.readFileSync(p, "utf8").replace(/\s+$/, "\n");

// @import MUST be the very first rule in the injected stylesheet, so the fonts
// file (which carries the Fredoka @import) always precedes everything else. The
// theme and overrides files have no @import. A browser silently drops any
// @import that follows another rule.
const fonts = read("src/sims2-fonts.css");
const theme = read("src/sims2-theme.css");
const overrides = read("src/sims2-overrides.css");
const css = fonts + "\n" + theme + "\n" + overrides;

// Once-only <style> injection. JSON.stringify turns the CSS into a safe
// double-quoted JS string (handles quotes, newlines, backslashes). Guarded so a
// double-registered resource never injects twice.
const styleInjection = [
  "/* --- document-level styles: sims2-fonts.css + sims2-theme.css (zero-config theme) + sims2-overrides.css, injected once at module load --- */",
  "(function () {",
  "  if (window.__sims2StylesInjected) return;",
  "  window.__sims2StylesInjected = true;",
  "  var style = document.createElement(\"style\");",
  "  style.id = \"sims2-bundle-styles\";",
  "  style.textContent = " + JSON.stringify(css) + ";",
  "  (document.head || document.documentElement).appendChild(style);",
  "})();",
  ""
].join("\n");

const banner = [
  "/*!",
  " * Sims 2 bundle for Home Assistant (sims2-bundle.js)",
  " * AUTO-GENERATED by build.sh — edit the files in src/ and rerun ./build.sh.",
  " * Bundles: the sims2: icon pack (52 icons), custom:sims2-loading,",
  " *           custom:sims2-plumbob, the document-level fonts + zero-config",
  " *           theme + overrides CSS, and a vendored copy of auto-entities",
  " *           (custom:auto-entities) so the auto-populating dashboards need no",
  " *           separate install.",
  " * Served and auto-registered as one module resource by the sims2ha integration.",
  " */",
  ""
].join("\n");

const section = (name) =>
  "\n/* ============================================================ " + name + " ============================================================ */\n";

const out =
  banner +
  styleInjection +
  section("sims2-icons.js — registers window.customIcons['sims2'] (52 icons)") +
  read("src/sims2-icons.js") +
  section("sims2-loading-card.js — customElements.define('sims2-loading')") +
  read("src/sims2-loading-card.js") +
  section("sims2-plumbob-card.js — customElements.define('sims2-plumbob')") +
  read("src/sims2-plumbob-card.js") +
  section("VENDORED DEP: auto-entities.js — MIT, (c) Thomas Lovén — customElements.define('auto-entities')") +
  "/* Vendored from thomasloven/lovelace-auto-entities so users need no separate */\n" +
  "/* HACS install. License: see src/vendor/auto-entities.LICENSE.txt in the repo. */\n" +
  read("src/vendor/auto-entities.js");

fs.writeFileSync("custom_components/sims2ha/frontend/sims2-bundle.js", out);
console.log("wrote custom_components/sims2ha/frontend/sims2-bundle.js: " + out.length + " bytes");
'
